#! /bin/sh

# sxhkd keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# bspwm
bspc monitor -d I II III IV

bspc config border_width            4
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bscp config pointer_follows_monitor true

# Colours

bspc config focused_border_color "#ffffff"
bspc config normal_border_color "#444444"
bspc config active_border_color "#ffffff"

# File explorer 
bspc rule -a File-roller state=floating


# Polybar init
$HOME/.config/polybar/launch.sh &

# Background and compositor
picom &
feh --bg-scale ~/Desktop/GpapPeaky/da/ASSETS/BG/ASCII3.png