#! /bin/sh

# sxhkd keybinds
pgrep -x sxhkd > /dev/null || sxhkd &

# bspwm
bspc monitor -d I II III

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.52
bspc config borderless_monocle      true
bspc config gapless_monocle         true
bscp config pointer_follows_monitor true

# Polybar init
$HOME/.config/polybar/launch.sh &

# Background
picom &
feh --bg-scale ~/Desktop/GpapPeaky/DA/ASSETS/BG/ASCII3.png